#!/bin/bash

# start script for the app in production
# set as the CMD part of the docker run command

# install any missing modules
cd /app
carton install --deployment

# setup runtime environment
export PERL5LIB=/app/lib:/app/local/lib/perl5
export PATH=$PATH:/app/local/bin
export MOJO_REACTOR=Mojo::Reactor::UV
export MOJO_MAX_MESSAGE_SIZE=65536   # default is 10485760 (10MB)
export MOJO_MODE=production
export MOJO_LOG_LEVEL=debug
APP_PORT=${APP_PORT:=3000}

# launch
script/sample_mojo_app daemon -l "http://0.0.0.0:${APP_PORT}"
