#!/bin/bash

# start script for the app, set as CMD of the docker run command

#APP_PORT default is 8105
APP_PORT=${APP_PORT:=3000}

# set Mojo params:
export LIBEV_FLAGS=4 # "use epoll"
export MOJO_MAX_MESSAGE_SIZE=65536   # default is 10485760 (10MB)
export MOJO_MODE=production

# launch
cd /app
script/sample_mojo_app daemon -l "http://0.0.0.0:${APP_PORT}"
